annotations:
  truecharts.org/category: GameServers
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 4.4.3
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Crafty Controller is a Minecraft Server Control Panel / Launcher.
home: https://truecharts.org/charts/stable/crafty-4
icon: https://gitlab.com/uploads/-/system/project/avatar/29382408/Crafty_4-0_Logo_square.png
keywords:
  - crafty-4
  - GameServers
  - Other
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: Taylortba	
    email: Admin@taylortba.com
    url: https://truecharts.org
name: crafty-4
sources:
  - https://craftycontrol.com/
  - https://github.com/Mark4562/Truenas-Scale/tree/main/stable/crafty-4
  - https://gitlab.com/crafty-controller/crafty-4
type: application
version: 8.1.5
